### PR TITLE
Removed ";" from vtkmacro setups to avoid pedantic errors in the downstream codes

### PR DESCRIPTION
**Pull request by ahmadhasan2k8**

### CODE REVIEW

**Comment by daviddoria** [comment]
Can you please separate the style/formatting changes from the removal of the semi-colon? I'm happy to also accept the style changes (separately) if they are more conformant to current VTK style.

**Comment by ahmadhasan2k8** [comment]
It's my sublime. Whenever I save file it formats everything according to clang format. I have made some other changes which is conforming to the current VTK style I believe which I will submit as a pull request later. I will separate the removal of semi-colons for now. Thanks

**Comment by ahmadhasan2k8** [comment]
Should be corrected now.

**Review by daviddoria — APPROVED** [review]

**Comment by daviddoria** [comment]
Thanks!


David

**Comment by ahmadhasan2k8** [comment]
Thanks

**Pull request merged**
